version: "3.8"
services:
  database-mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=DBBookingCare
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - '3308:3306'

  backend:
    build:
      context: ../BackEnd
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # - DB_PORT=3306
      # - DB_HOST=db
      - DB_HOST=host.docker.internal
    ports:
      - 8080:8080

  # docker-compose -p hoidanit-nodejs-mysql up -d

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../FontEnd/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    # docker compose -p hoidanit-nginx up -d
