version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=DBBookingCare
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - '3308:3306'

#docker compose -p bookingcare-mysql up -d